### PR TITLE
Styled De/activation Confirmations (JS Alerts)

### LINKED ISSUE #155: Styled De/activation Confirmations (JS Alerts)
# Summary

When deactivating a volunteer/student/admin, the default browser JS alert confirms the user's action. These alerts should be in the style of InKind UX/UI.

# Criteria for Completion
 - [ ] Current functionality remains intact. Activating & deactivating a student/volunteer/admin pops a confirmation alert.
 - [ ] The new alert matches the provided mockup

## What the alert looks like now (or whatever your specific browser does):

Screen Shot 2021-11-28 at 1 07 01 PM

## How the alert should look after this change:

Screen Shot 2021-11-28 at 1 06 24 PM

### PR DESCRIPTION
**Pull request by JelenaD1**
Resolves #155 

This PR is adding a sweet alert library to style alert messages in the app. 

### Description

Sweetalert2 gem was added to Gemfile and package.json. 

### Type of change

New feature that styles the alert messages.

### Screenshots

Volunteers___INKIND

_volunteers_table_html_erb_—_inkind-admin

### CODE REVIEW

**Comment by JelenaD1** [comment]
Hey @garettarrowood , me and @RudeChowder just finished with adding style alert. We will open a new PR and add updated the alert messages to use sweetalert. Let us know if any changes are needed.

**Comment by garettarrowood** [comment]
Looks good @JelenaD1 & @RudeChowder !

Be sure to make the text in the buttons all CAPS. And see if you can get rid of the big yellow circle with the explanation mark in it.

**Comment by JelenaD1** [comment]
@garettarrowood That circle is an icon and we can easily remove it. I'll update it tonight.

**Comment by JelenaD1** [comment]
@garettarrowood This is done. I've updated the pages and a screenshots. I'm not sure if I need to write docs on default values- I've added info on the second screenshot for you to see it.

**Comment by garettarrowood** [comment]
Hmm.... why is CI not running on this anymore...

**Comment by garettarrowood** [comment]
Looks like CI got a little misconfigured recently and isn't running on PRs. I've updated the github workflow to fix this (I think). Could you pull and merge upstream master into this so CI runs?

**Comment by JelenaD1** [comment]
> Looks like CI got a little misconfigured recently and isn't running on PRs. I've updated the github workflow to fix this (I think). Could you pull and merge upstream master into this so CI runs?

I did pull from master beforehand. I also tried again and it says my local branch is up to date, unless I am doing it wrong.
jelenadurovic_Jelenas-MacBook-Pro___Desktop_inkind-admin

**Comment by garettarrowood** [comment]
Try first pulling upstream main. So first checkout your local main branch. Then `git pull upstream main`. Then go back to your branch. Then `git rebase origin/main`.

**Comment by JelenaD1** [comment]
> Try first pulling upstream main. So first checkout your local main branch. Then `git pull upstream main`. Then go back to your branch. Then `git rebase origin/main`.

Hey @garettarrowood , me and @RudeChowder just pull upstream and got latest from main repo. CI finally started running, BUT it looks like it failed during the setup: https://github.com/rubyforgood/inkind-admin/runs/5079900367?check_suite_focus=true

**Comment by garettarrowood** [comment]
Pull upstream one more time. The Azure check in CI has been removed.

**Comment by JelenaD1** [comment]
> Pull upstream one more time. The Azure check in CI has been removed.

Will do. Thanks @garettarrowood

**Review by garettarrowood — APPROVED** [review]

**Pull request merged**
