### PR TITLE
Updated Organization form

### LINKED ISSUE #160: Update Organization Form
# Summary

Update the styles on the Organization form to match the mockup.

## Things to Consider

The student form has the most up-to-date-ish styling so far. Feel free to reference that to align conventions.

# Criteria for Completion
 - [ ] Organization form looks like the attached mockup
 - [ ] The form still works, saving all fields.

## How it looks now:

Screen Shot 2021-11-28 at 4 18 48 PM

## How it will look after this change:

Note: Keep City/State easy. They should be two separate inputs, as they are stored on the table.

Screen Shot 2021-11-28 at 4 18 09 PM

### PR DESCRIPTION
**Pull request by Ashvith**
Resolves #160

### Description
- Added a CSS style for input-text (`.text-input-common`).
- Applied the style for the textboxes, except for a few (mentioned below).
- Also added the buttons **Save** and **Cancel** (with their respective button styles).
- Did not include the **Phone** text box.
- Did not join the **City** and **State** text box into a single, dropdown textbox.

### Type of change

* Bug fix (non-breaking change which fixes an issue)

### Screenshots
Screenshot from 2021-12-10 20-17-01

### CODE REVIEW

**Comment by garettarrowood** [comment]
Looking great so far!

Could you:

1. Add the "Back" link at the top (see other forms)
2. Make the City and State inputs half the width (check out the Student form)
3. Make the State input a typeahead select (again, check the Student form for this. It should be as easy as copying over the same f.input configurations. `Carmen` was recently added to pull geographical regions)

**Comment by Ashvith** [comment]
1. I did not add the "Back" button because the code for **Cancel** and **Back** would have been the same then, but if it is needed, then I'll do as per the requirement.
2. This should be easy to work with.
3. I'll have a quick look, this should probably be easy as well.

**Comment by garettarrowood** [comment]
Looks like you've made the upgrades. Could you post an updated screenshot?

**Comment by Ashvith** [comment]
Sorry for the delayed reply, here is a screenshot of the same. I was not able to figure out how to increase the padding of the select form below.
Screenshot from 2021-12-15 09-01-39

**Comment by garettarrowood** [comment]
No worries, this looks great! Thank you for this contribution!

**Review by garettarrowood — APPROVED** [review]

**Pull request merged**
