### PR TITLE
#132 Check Fluent Icons into codebase instead of pulling from `node_modules`

### LINKED ISSUE #132: Check Fluent Icons into codebase instead of pulling from `node_modules`
# Summary

As a developer, I do not want InKind's icons to break with a dependency upgrade.

## Things to Consider

The Fluent icons in the sidebar looks and work great! But the svgs are getting pulled from `node_modules/*`, which means if the fluent library decides to move their icons around, they won't render in the app anymore.

This is easy to fix! We should check the `svg`s directly into the codebase so there is no chance they could move directories and break the nav in the future.

# Criteria for Completion
 - [ ] Icons are checked into the repo and linked directly from the codebase.
 - [ ] Sidebar nav looks and works the same.

### PR DESCRIPTION
**Pull request by RudeChowder**
Resolves #132

### Description

We downloaded the icons and added them to the assets/images/icons folder. We removed the references to node_modules and are instead now using the local copies.
We updated all the icons for the sidebar, and also noticed the topbar was using two icons as well. We changed them too. The page should continue to function properly even if the fluent library makes changes on their end.

Tested in the browser that the icons still behave correctly.

### Type of change

* New feature (non-breaking change which adds functionality)

### Screenshots

updated_icons

### CODE REVIEW

**Comment by garettarrowood** [comment]
Great! Could you:

1. Upload a screenshot so I can see all is working?
2. Remove the now unused `@fluentui/svg-icons` from the `package.json` & regen the `yarn.lock`?

**Comment by JelenaD1** [comment]
Sure. Working on it right now.

**Comment by RudeChowder** [comment]
We added a screenshot to the main PR body and also removed the dependency. Let us know if this one needs anything else.

**Review by garettarrowood — APPROVED** [review]
Awesome work! Thank you for this contribution!

**Pull request merged**
